name: GUI, API and Components Tests

on:
  push:
    branches:
      - main  

jobs:
  SETUP:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install

  API-TESTS:
    needs: SETUP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install backend
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Install frontend

      - name: Run API tests
        uses: cypress-io/github-action@v6
        with:
         start: npm run start:server
         command: npm run api:run

  ACCESSIBILITY-TESTS:
    needs: SETUP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install backend
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Install frontend
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Run Accessibility tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:frontend, npm run start:server
          command: npm run accessibility:run
